<div class="row form-podcast">
    <form method="post" action="<?= PAGE_BASE; ?>admin/config">
        <div class="col-lg-3 col-md-6">
            <div class="row">
                <h3>Global Settings</h3>

            </div>
        </div>
        <div class="col-xs-12">
            <? foreach($action['config'] as $key => $c) : ?>
            <div class="row">
                <div class="col-xs-6">
                    <input type="text" name="configForm[<?= $key; ?>]" value="<?= $c; ?>" class="form-control">
                </div>
                <div class="col-xs-6 config-label">
                    <?= $key; ?>
                </div>
            </div>
            <? endforeach; ?>
        </div>
        <div class="col-xs-12">
            <div class="row">
                <div class="col-xs-12 mt">
                    <button type="submit" class="btn btn-success" id="button-save">save</a>
                </div>
            </div>
        </div>
</div>
</form>