<?
	global $_p;

 /*?>
			<div class="footer">
				&copy; seit 2012 <a href="<?= PAGE_BASE; ?>"><?= PAGE_NAME; ?></a>
				&middot; <a href="<?= PAGE_BASE; ?>impressum">Impressum</a>
				&middot; <a href="<?= PAGE_BASE; ?>datenschutz">Datenschutz</a>
				&middot; <a href="<?= PAGE_BASE; ?>nutzungsbedingungen">Nutzungsbedingungen</a>
				&middot; <a href="<?= PAGE_BASE; ?>agbs">AGBs</a>
			</div>

 */ ?>