<?
$message=$action['message'];
global $_u,$_p;
?>
<div class="">
    <div class="row-fluid">
        <? if(!empty($message)) : ?>
        <ul class="action-message deny">
            <li class="" style=""><?= $message; ?></li>
        </ul>
        <?  endif; ?>
        
        <div class="well">
            <form action="<?= PAGE_BASE; ?>login" method="POST">
                <div class="row oh">
                    <div class="well">
                        <h3>Login</h3>
                    </div>
                    <div class="col-md-12">
                        <div>
                            <input type="password" name="login[secret]"  class="form-control tac" placeholder="password" autocomplete="off">
                        </div>
                    </div>
                </div>
                <div class="row oh">
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-success btn-large col-xs-12">Login</button>
                    </div>
                </div>
                
            </form>
        </div>
        <div class="span4"></div>
    </div>
</div>