<?
global $_p, $_c;
 ?>
<div id="overlay" style="display:none;"></div>
<a href="" class="btn btn-primary button-open-mainmenu" id="open-main-menu"><i class="fa fa-bars"></i></a>
<div id="main-navigation" class="header-right" style="display:none;">
    <?= $_c -> partial('header-main-navigation', $action); ?>
</div>
<div class="page-header">
    <div class="header-left">
        <h2><?= PAGE_NAME; ?> <?= PAGE_CLAIM; ?> - <?= $_p -> content['label']; ?> <a href="" class="button-add-podcast"><i class="fa fa fa-plus-square-o"></i> new</a></h2>
    </div>   
</div>
<div class="col-xs-12 col-sm-6" id="FormPodcast">
    <?= $_c -> partial('podcast/form', $action); ?>
</div>
<div class="col-xs-12 col-sm-6" id="ListingPodcast">
    <?= $_c -> partial('podcast/listing', $action); ?>
</div>
